// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCG_CollectionGame.DataContext;

namespace TCG_CollectionGame.Data.Migrations
{
    [DbContext(typeof(TCG_CollectionGameContext))]
    [Migration("20220530093017_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.Pokecard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokesetID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PokesetID");

                    b.HasIndex("UserID");

                    b.ToTable("Pokecard");
                });

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.Pokeset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pokeset");
                });

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.Trade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Card1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Card2ID")
                        .HasColumnType("int");

                    b.Property<int?>("User1ID")
                        .HasColumnType("int");

                    b.Property<int?>("User2ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Card1ID");

                    b.HasIndex("Card2ID");

                    b.HasIndex("User1ID");

                    b.HasIndex("User2ID");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Coin")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.Pokecard", b =>
                {
                    b.HasOne("TCG_CollectionGame.Entities.Models.Pokeset", "Pokeset")
                        .WithMany("Cards")
                        .HasForeignKey("PokesetID");

                    b.HasOne("TCG_CollectionGame.Entities.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("TCG_CollectionGame.Entities.Models.Trade", b =>
                {
                    b.HasOne("TCG_CollectionGame.Entities.Models.Pokecard", "Card1")
                        .WithMany()
                        .HasForeignKey("Card1ID");

                    b.HasOne("TCG_CollectionGame.Entities.Models.Pokecard", "Card2")
                        .WithMany()
                        .HasForeignKey("Card2ID");

                    b.HasOne("TCG_CollectionGame.Entities.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1ID");

                    b.HasOne("TCG_CollectionGame.Entities.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2ID");
                });
#pragma warning restore 612, 618
        }
    }
}
