// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCG_CollectionGame.DataContext;

namespace TCG_CollectionGame.Data.Migrations
{
    [DbContext(typeof(TCG_CollectionGameContext))]
    [Migration("20220524123534_Joins_And_Seed")]
    partial class Joins_And_Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCG_CollectionGame.Enities.Models.Pokecard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokesetID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PokesetID");

                    b.HasIndex("UserID");

                    b.ToTable("Pokecard");
                });

            modelBuilder.Entity("TCG_CollectionGame.Enities.Models.Pokeset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pokeset");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SetCode = "base1",
                            SetName = "Base"
                        },
                        new
                        {
                            ID = 2,
                            SetCode = "base2",
                            SetName = "Jungle"
                        },
                        new
                        {
                            ID = 3,
                            SetCode = "basep",
                            SetName = "Wizards Black Star Promos"
                        },
                        new
                        {
                            ID = 4,
                            SetCode = "base3",
                            SetName = "Fossil"
                        },
                        new
                        {
                            ID = 5,
                            SetCode = "base4",
                            SetName = "Base Set 2"
                        },
                        new
                        {
                            ID = 6,
                            SetCode = "base5",
                            SetName = "Team Rocket"
                        },
                        new
                        {
                            ID = 7,
                            SetCode = "gym1",
                            SetName = "Gym Heroes"
                        },
                        new
                        {
                            ID = 8,
                            SetCode = "gym2",
                            SetName = "Gym Challenge"
                        },
                        new
                        {
                            ID = 9,
                            SetCode = "neo1",
                            SetName = "Neo Genesis"
                        },
                        new
                        {
                            ID = 10,
                            SetCode = "neo2",
                            SetName = "Neo Discovery"
                        },
                        new
                        {
                            ID = 11,
                            SetCode = "si1",
                            SetName = "Southern Islands"
                        },
                        new
                        {
                            ID = 12,
                            SetCode = "neo3",
                            SetName = "Neo Revelation"
                        },
                        new
                        {
                            ID = 13,
                            SetCode = "neo4",
                            SetName = "Neo Destiny"
                        },
                        new
                        {
                            ID = 14,
                            SetCode = "base6",
                            SetName = "Legendary Collection"
                        },
                        new
                        {
                            ID = 15,
                            SetCode = "ecard1",
                            SetName = "Expedition Base Set"
                        },
                        new
                        {
                            ID = 16,
                            SetCode = "ecard2",
                            SetName = "Aquapolis"
                        },
                        new
                        {
                            ID = 17,
                            SetCode = "ecard3",
                            SetName = "Skyridge"
                        },
                        new
                        {
                            ID = 18,
                            SetCode = "ex1",
                            SetName = "Ruby & Sapphire"
                        },
                        new
                        {
                            ID = 19,
                            SetCode = "ex3",
                            SetName = "Dragon"
                        },
                        new
                        {
                            ID = 20,
                            SetCode = "ex2",
                            SetName = "Sandstorm"
                        },
                        new
                        {
                            ID = 21,
                            SetCode = "np",
                            SetName = "Nintendo Black Star Promos"
                        },
                        new
                        {
                            ID = 22,
                            SetCode = "ex4",
                            SetName = "Team Magma vs Team Aqua"
                        },
                        new
                        {
                            ID = 23,
                            SetCode = "ex5",
                            SetName = "Hidden Legends"
                        },
                        new
                        {
                            ID = 24,
                            SetCode = "ex6",
                            SetName = "FireRed & LeafGreen"
                        },
                        new
                        {
                            ID = 25,
                            SetCode = "pop1",
                            SetName = "POP Series 1"
                        },
                        new
                        {
                            ID = 26,
                            SetCode = "ex7",
                            SetName = "Team Rocket Returns"
                        },
                        new
                        {
                            ID = 27,
                            SetCode = "ex8",
                            SetName = "Deoxys"
                        },
                        new
                        {
                            ID = 28,
                            SetCode = "ex9",
                            SetName = "Emerald"
                        },
                        new
                        {
                            ID = 29,
                            SetCode = "ex10",
                            SetName = "Unseen Forces"
                        },
                        new
                        {
                            ID = 30,
                            SetCode = "pop2",
                            SetName = "POP Series 2"
                        },
                        new
                        {
                            ID = 31,
                            SetCode = "ex11",
                            SetName = "Delta Species"
                        },
                        new
                        {
                            ID = 32,
                            SetCode = "ex12",
                            SetName = "Legend Maker"
                        },
                        new
                        {
                            ID = 33,
                            SetCode = "pop3",
                            SetName = "POP Series 3"
                        },
                        new
                        {
                            ID = 34,
                            SetCode = "ex13",
                            SetName = "Holon Phantoms"
                        },
                        new
                        {
                            ID = 35,
                            SetCode = "pop4",
                            SetName = "POP Series 4"
                        },
                        new
                        {
                            ID = 36,
                            SetCode = "ex14",
                            SetName = "Crystal Guardians"
                        },
                        new
                        {
                            ID = 37,
                            SetCode = "ex15",
                            SetName = "Dragon Frontiers"
                        },
                        new
                        {
                            ID = 38,
                            SetCode = "ex16",
                            SetName = "Power Keepers"
                        },
                        new
                        {
                            ID = 39,
                            SetCode = "pop5",
                            SetName = "POP Series 5"
                        },
                        new
                        {
                            ID = 40,
                            SetCode = "dp1",
                            SetName = "Diamond & Pearl"
                        },
                        new
                        {
                            ID = 41,
                            SetCode = "dpp",
                            SetName = "DP Black Star Promos"
                        },
                        new
                        {
                            ID = 42,
                            SetCode = "dp2",
                            SetName = "Mysterious Treasures"
                        },
                        new
                        {
                            ID = 43,
                            SetCode = "pop6",
                            SetName = "POP Series 6"
                        },
                        new
                        {
                            ID = 44,
                            SetCode = "dp3",
                            SetName = "Secret Wonders"
                        },
                        new
                        {
                            ID = 45,
                            SetCode = "dp4",
                            SetName = "Great Encounters"
                        },
                        new
                        {
                            ID = 46,
                            SetCode = "pop7",
                            SetName = "POP Series 7"
                        },
                        new
                        {
                            ID = 47,
                            SetCode = "dp5",
                            SetName = "Majestic Dawn"
                        },
                        new
                        {
                            ID = 48,
                            SetCode = "dp6",
                            SetName = "Legends Awakened"
                        },
                        new
                        {
                            ID = 49,
                            SetCode = "pop8",
                            SetName = "POP Series 8"
                        },
                        new
                        {
                            ID = 50,
                            SetCode = "dp7",
                            SetName = "Stormfront"
                        },
                        new
                        {
                            ID = 51,
                            SetCode = "pl1",
                            SetName = "Platinum"
                        },
                        new
                        {
                            ID = 52,
                            SetCode = "pop9",
                            SetName = "POP Series 9"
                        },
                        new
                        {
                            ID = 53,
                            SetCode = "pl2",
                            SetName = "Rising Rivals"
                        },
                        new
                        {
                            ID = 54,
                            SetCode = "pl3",
                            SetName = "Supreme Victors"
                        },
                        new
                        {
                            ID = 55,
                            SetCode = "pl4",
                            SetName = "Arceus"
                        },
                        new
                        {
                            ID = 56,
                            SetCode = "ru1",
                            SetName = "Pokemon Rumble"
                        },
                        new
                        {
                            ID = 57,
                            SetCode = "hsp",
                            SetName = "HGSS Black Star Promos"
                        },
                        new
                        {
                            ID = 58,
                            SetCode = "hgss1",
                            SetName = "HeartGold & SoulSilver"
                        },
                        new
                        {
                            ID = 59,
                            SetCode = "hgss2",
                            SetName = "HS-Unleashed"
                        },
                        new
                        {
                            ID = 60,
                            SetCode = "hgss3",
                            SetName = "HS-Undaunted"
                        },
                        new
                        {
                            ID = 61,
                            SetCode = "hgss4",
                            SetName = "HS-Triumphant"
                        },
                        new
                        {
                            ID = 62,
                            SetCode = "col1",
                            SetName = "Call of Legends"
                        },
                        new
                        {
                            ID = 63,
                            SetCode = "bwp",
                            SetName = "BW Black Star Promos"
                        },
                        new
                        {
                            ID = 64,
                            SetCode = "bw1",
                            SetName = "Black & White"
                        },
                        new
                        {
                            ID = 65,
                            SetCode = "bw2",
                            SetName = "Emerging Powers"
                        },
                        new
                        {
                            ID = 66,
                            SetCode = "bw3",
                            SetName = "Noble Victories"
                        },
                        new
                        {
                            ID = 67,
                            SetCode = "bw4",
                            SetName = "Next Destinies"
                        },
                        new
                        {
                            ID = 68,
                            SetCode = "bw5",
                            SetName = "Dark Explorers"
                        },
                        new
                        {
                            ID = 69,
                            SetCode = "bw6",
                            SetName = "Dragons Exalted"
                        },
                        new
                        {
                            ID = 70,
                            SetCode = "dv1",
                            SetName = "Dragon Vault"
                        },
                        new
                        {
                            ID = 71,
                            SetCode = "bw7",
                            SetName = "Boundaries Crossed"
                        },
                        new
                        {
                            ID = 72,
                            SetCode = "bw8",
                            SetName = "Plasma Storm"
                        },
                        new
                        {
                            ID = 73,
                            SetCode = "bw9",
                            SetName = "Plasma Freeze"
                        },
                        new
                        {
                            ID = 74,
                            SetCode = "bw10",
                            SetName = "Plasma Blast"
                        },
                        new
                        {
                            ID = 75,
                            SetCode = "xyp",
                            SetName = "XY Black Star Promos"
                        },
                        new
                        {
                            ID = 76,
                            SetCode = "bw11",
                            SetName = "Legendary Treasures"
                        },
                        new
                        {
                            ID = 77,
                            SetCode = "xy0",
                            SetName = "Kalos Starter Set"
                        },
                        new
                        {
                            ID = 78,
                            SetCode = "xy1",
                            SetName = "XY"
                        },
                        new
                        {
                            ID = 79,
                            SetCode = "xy2",
                            SetName = "Flashfire"
                        },
                        new
                        {
                            ID = 80,
                            SetCode = "xy3",
                            SetName = "Furious Fists"
                        },
                        new
                        {
                            ID = 81,
                            SetCode = "xy4",
                            SetName = "Phantom Forces"
                        },
                        new
                        {
                            ID = 82,
                            SetCode = "xy5",
                            SetName = "Primal Clash"
                        },
                        new
                        {
                            ID = 83,
                            SetCode = "dc1",
                            SetName = "Double Crisis"
                        },
                        new
                        {
                            ID = 84,
                            SetCode = "xy6",
                            SetName = "Roaring Skies"
                        },
                        new
                        {
                            ID = 85,
                            SetCode = "xy7",
                            SetName = "Ancient Origins"
                        },
                        new
                        {
                            ID = 86,
                            SetCode = "xy8",
                            SetName = "BREAKthrough"
                        },
                        new
                        {
                            ID = 87,
                            SetCode = "xy9",
                            SetName = "BREAKpoint"
                        },
                        new
                        {
                            ID = 88,
                            SetCode = "g1",
                            SetName = "Generations"
                        },
                        new
                        {
                            ID = 89,
                            SetCode = "xy10",
                            SetName = "Fates Collide"
                        },
                        new
                        {
                            ID = 90,
                            SetCode = "xy11",
                            SetName = "Steam Siege"
                        },
                        new
                        {
                            ID = 91,
                            SetCode = "xy12",
                            SetName = "Evolutions"
                        },
                        new
                        {
                            ID = 92,
                            SetCode = "smp",
                            SetName = "SM Black Star Promos"
                        },
                        new
                        {
                            ID = 93,
                            SetCode = "sm1",
                            SetName = "Sun & Moon"
                        },
                        new
                        {
                            ID = 94,
                            SetCode = "sm2",
                            SetName = "Guardians Rising"
                        },
                        new
                        {
                            ID = 95,
                            SetCode = "sm3",
                            SetName = "Burning Shadows"
                        },
                        new
                        {
                            ID = 96,
                            SetCode = "sm35",
                            SetName = "Shining Legends"
                        },
                        new
                        {
                            ID = 97,
                            SetCode = "sm4",
                            SetName = "Crimson Invasion"
                        },
                        new
                        {
                            ID = 98,
                            SetCode = "sm5",
                            SetName = "Ultra Prism"
                        },
                        new
                        {
                            ID = 99,
                            SetCode = "sm6",
                            SetName = "Forbidden Light"
                        },
                        new
                        {
                            ID = 100,
                            SetCode = "sm7",
                            SetName = "Celestial Storm"
                        },
                        new
                        {
                            ID = 101,
                            SetCode = "sm75",
                            SetName = "Dragon Majesty"
                        },
                        new
                        {
                            ID = 102,
                            SetCode = "sm8",
                            SetName = "Lost Thunder"
                        },
                        new
                        {
                            ID = 103,
                            SetCode = "sm9",
                            SetName = "Team Up"
                        },
                        new
                        {
                            ID = 104,
                            SetCode = "det1",
                            SetName = "Detective Pikachu"
                        },
                        new
                        {
                            ID = 105,
                            SetCode = "sm10",
                            SetName = "Unbroken Bonds"
                        },
                        new
                        {
                            ID = 106,
                            SetCode = "sm11",
                            SetName = "Unified Minds"
                        },
                        new
                        {
                            ID = 107,
                            SetCode = "sm115",
                            SetName = "Hidden Fates"
                        },
                        new
                        {
                            ID = 108,
                            SetCode = "sma",
                            SetName = "Shiny Vault"
                        },
                        new
                        {
                            ID = 109,
                            SetCode = "sm12",
                            SetName = "Cosmic Eclipse"
                        },
                        new
                        {
                            ID = 110,
                            SetCode = "swshp",
                            SetName = "SWSH Black Star Promos"
                        },
                        new
                        {
                            ID = 111,
                            SetCode = "swsh1",
                            SetName = "Sword & Shield"
                        },
                        new
                        {
                            ID = 112,
                            SetCode = "swsh2",
                            SetName = "Rebel Clash"
                        },
                        new
                        {
                            ID = 113,
                            SetCode = "swsh3",
                            SetName = "Darkness Ablaze"
                        },
                        new
                        {
                            ID = 114,
                            SetCode = "swsh35",
                            SetName = "Champion's Path"
                        },
                        new
                        {
                            ID = 115,
                            SetCode = "swsh4",
                            SetName = "Vivid Voltage"
                        },
                        new
                        {
                            ID = 116,
                            SetCode = "swsh45",
                            SetName = "Shining Fates"
                        },
                        new
                        {
                            ID = 117,
                            SetCode = "swsh45sv",
                            SetName = "Shiny Vault"
                        },
                        new
                        {
                            ID = 118,
                            SetCode = "swsh5",
                            SetName = "Battle Styles"
                        },
                        new
                        {
                            ID = 119,
                            SetCode = "swsh6",
                            SetName = "Chilling Reign"
                        });
                });

            modelBuilder.Entity("TCG_CollectionGame.Enities.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Coin")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TCG_CollectionGame.Enities.Models.Pokecard", b =>
                {
                    b.HasOne("TCG_CollectionGame.Enities.Models.Pokeset", "Pokeset")
                        .WithMany("Cards")
                        .HasForeignKey("PokesetID");

                    b.HasOne("TCG_CollectionGame.Enities.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
